"""
Script to compile all chapters into a single book file
"""

import glob
from pathlib import Path
import re

def compile_book():
    # Create output directory if it doesn't exist
    output_dir = Path("story_data/compiled")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Find all chapter files
    chapter_files = []
    chapters_dir = Path("story_data/chapters")
    for chapter_num in range(1, 8):
        pattern = f"chapter_{chapter_num:03d}_*.txt"
        matches = list(chapters_dir.glob(pattern))
        if matches:
            # Sort by timestamp to get the latest version
            latest = sorted(matches, key=lambda x: x.stem.split('_')[2])[-1]
            chapter_files.append(latest)
    
    # Compile the book
    book_content = """Digital Consciousness

A Novel Generated by AI

===================================

"""
    
    # Add each chapter
    for chapter_file in sorted(chapter_files):
        with open(chapter_file, 'r', encoding='utf-8') as f:
            content = f.read()
            # Remove the "Here's Chapter X" line that some chapters have
            content = re.sub(r"Here's Chapter \d+ of.*?\n\n", "", content)
            book_content += content + "\n\n" + "=" * 50 + "\n\n"
    
    # Save the compiled book
    output_file = output_dir / "Digital_Consciousness.txt"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(book_content)
    
    return output_file

if __name__ == "__main__":
    output_file = compile_book()
    print(f"Book compiled successfully to: {output_file}")
